# docker-compose up -d # daemon
services:
  # docker-compose up -d mysql
  mysql:
    image: mysql:latest
    # command: --mysql-native-password=ON
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    privileged: true
    restart: on-failure
    environment:
      # MYSQL_NATIVE_PASSWORD: ON
      # MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db0
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      TZ: Asia/Shanghai
  # docker-compose down mysql -v

  # docker-compose up -d redis
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    privileged: true
    restart: on-failure
  # docker-compose down redis -v

  # docker-compose up -d mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    privileged: true
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    # docker-compose down mongo -v

  # docker-compose up -d nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "8080:8080"
    privileged: true
    restart: on-failure
    environment:
      NGINX_PORT: 80
    # volumes:
    #   - .volumes/etc/nginx/conf.d:/etc/nginx/conf.d
    #   - .volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - .volumes/usr/share/nginx/html:/usr/share/nginx/html
  # docker-compose down nginx -v
# docker-compose down -v # volume
